#!/bin/sh

rm -rf /usr/share/themes/maemo-org-theme-folder/gtk-2.0/*.cache

if [ "`readlink /etc/hildon/theme`" = /usr/share/themes/maemo-org-theme-folder ]; then
   if [ -x /usr/bin/personalisation ]; then
	   /usr/bin/personalisation /usr/share/themes/default
   fi
fi
